/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "source/peopleController.sv:1.1-318.10" *)
module peopleController(clk, rst, simState, simSpeed, people, elevatorStates, randy, peopleGenerated, xposCFF, yposCFF, floorsRequested);
  (* src = "source/peopleController.sv:61.24-61.31" *)
  wire [62:0] arrived;
  (* src = "source/peopleController.sv:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "source/peopleController.sv:219.24-219.31" *)
  wire [62:0] dropoff;
  (* src = "source/peopleController.sv:6.23-6.37" *)
  input [5:0] elevatorStates;
  wire [5:0] elevatorStates;
  (* src = "source/peopleController.sv:12.25-12.40" *)
  output [11:0] floorsRequested;
  wire [11:0] floorsRequested;
  (* src = "source/peopleController.sv:279.24-279.40" *)
  wire [62:0] foundDestination;
  (* src = "source/peopleController.sv:5.29-5.35" *)
  input [5:0] people;
  wire [5:0] people;
  (* src = "source/peopleController.sv:8.30-8.45" *)
  output [5:0] peopleGenerated;
  wire [5:0] peopleGenerated;
  (* src = "source/peopleController.sv:63.24-63.27" *)
  wire [62:0] pos;
  (* src = "source/peopleController.sv:7.23-7.28" *)
  input [9:0] randy;
  wire [9:0] randy;
  (* src = "source/peopleController.sv:62.24-62.28" *)
  wire [62:0] ride;
  (* hdlname = "rngCounter clk" *)
  (* src = "source/counterParametric.sv:2.17-2.20" *)
  (* unused_bits = "0" *)
  wire \rngCounter.clk ;
  (* hdlname = "rngCounter en" *)
  (* src = "source/counterParametric.sv:2.27-2.29" *)
  wire \rngCounter.en ;
  (* hdlname = "rngCounter rst" *)
  (* src = "source/counterParametric.sv:2.22-2.25" *)
  (* unused_bits = "0" *)
  wire \rngCounter.rst ;
  (* src = "source/peopleController.sv:3.22-3.25" *)
  input rst;
  wire rst;
  (* src = "source/peopleController.sv:4.33-4.41" *)
  input [1:0] simSpeed;
  wire [1:0] simSpeed;
  (* src = "source/peopleController.sv:4.23-4.31" *)
  input [1:0] simState;
  wire [1:0] simState;
  (* hdlname = "twenty clk" *)
  (* src = "source/counterParametric.sv:2.17-2.20" *)
  (* unused_bits = "0" *)
  wire \twenty.clk ;
  (* hdlname = "twenty en" *)
  (* src = "source/counterParametric.sv:2.27-2.29" *)
  wire \twenty.en ;
  (* hdlname = "twenty rst" *)
  (* src = "source/counterParametric.sv:2.22-2.25" *)
  (* unused_bits = "0" *)
  wire \twenty.rst ;
  (* src = "source/peopleController.sv:10.34-10.41" *)
  output [629:0] xposCFF;
  wire [629:0] xposCFF;
  (* src = "source/peopleController.sv:47.27-47.36" *)
  wire [629:0] xposCFF_n;
  (* src = "source/peopleController.sv:241.23-241.32" *)
  wire [62:0] xposDFF_e;
  (* src = "source/peopleController.sv:11.33-11.40" *)
  output [188:0] yposCFF;
  wire [188:0] yposCFF;
  (* src = "source/peopleController.sv:242.24-242.33" *)
  wire [62:0] yposCFF_e;
  (* src = "source/peopleController.sv:210.26-210.35" *)
  wire [188:0] yposCFF_n;
  (* src = "source/peopleController.sv:243.26-243.35" *)
  wire [125:0] yposDFF_e;
  assign arrived = 63'h0000000000000000;
  assign dropoff = 63'h0000000000000000;
  assign floorsRequested = 12'h000;
  assign foundDestination = 63'h0000000000000000;
  assign peopleGenerated = 6'hxx;
  assign pos = 63'h0000000000000000;
  assign ride = 63'h0000000000000000;
  assign \rngCounter.clk  = clk;
  assign \rngCounter.en  = 1'h1;
  assign \rngCounter.rst  = rst;
  assign \twenty.clk  = clk;
  assign \twenty.en  = 1'h1;
  assign \twenty.rst  = rst;
  assign xposCFF = 630'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
  assign xposCFF_n = 630'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign xposDFF_e = 63'h0000000000000000;
  assign yposCFF = 189'h000000000000000000000000000000000000000000000000;
  assign yposCFF_e = 63'h0000000000000000;
  assign yposCFF_n = 189'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign yposDFF_e = 126'h00000000000000000000000000000000;
endmodule
